dist: xenial

addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8'
      key_url: 'https://bazel.build/bazel-release.pub.gpg'
    packages:
    - bazel

script:
  - bazel version
  - cd examples
  # build examples first to populate shared repository cache which is read-only during testing
  - bazel build //antlr2/Cpp/... //antlr4/Go/...
  - cd ..
  - bazel test --jobs 2 --test_output=errors //...
  - bazel shutdown

language: java

