dist: xenial

addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8'
      key_url: 'https://bazel.build/bazel-release.pub.gpg'
    packages:
    - bazel

script:
  - bazel version
  - cd examples
  # build examples first to populate shared repository cache which is read-only during testing
  - bazel build --jobs 2 //antlr2/Cpp/... //antlr2/Python/... //antlr3/Python2/... //antlr3/Python3/... //antlr4/Go/... //antlr4/Python2/... //antlr4/Python3/...
  - cd ..
  - bazel test --jobs 2 --test_output=errors //...
  - bazel shutdown

language: java

